name: Create a release

on:
  #push:
  #branches: [ "main" ]
  #pull_request:
  #branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps:
      - name : Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
        id: android_version
      - name: Get version
        run: |
          echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: echo "Building APK."  
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "Build status report=${{ job.status }}."
      - name: Archive APK Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: lab31kbd-${{env.version_name}}-apk.zip
          directory: app/build/outputs/apk/release
      - name: Android APK Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{env.version_name}}
          tag_name: ${{env.version_name}}
          prerelease: false
          files: app/build/outputs/apk/release/lab31kbd-${{env.version_name}}-apk.zip
